# Generated by Django 4.1.5 on 2023-01-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sneaker_brand', models.CharField(max_length=50)),
                ('sneaker_model', models.CharField(max_length=50)),
                ('sneaker_name', models.CharField(max_length=100)),
                ('sneaker_colorway', models.CharField(max_length=100)),
                ('sneaker_size', models.CharField(max_length=20)),
                ('release_year', models.CharField(max_length=20)),
                ('retail_price', models.CharField(max_length=20)),
                ('cover_image', models.CharField(max_length=300)),
            ],
        ),
    ]
