# Generated by Django 4.1.5 on 2023-01-19 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sneakerModels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sneakerModels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sneakerModels.sneakermodels')),
            ],
        ),
    ]
