# Generated by Django 4.1.5 on 2023-01-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SneakerModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('colorway', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=20)),
                ('release_year', models.CharField(max_length=20)),
                ('retail_price', models.CharField(max_length=20)),
                ('cover_image', models.CharField(max_length=300)),
                ('sneaker_model', models.ManyToManyField(blank=True, related_name='models', to='brands.brand')),
            ],
        ),
    ]
