# Generated by Django 4.1.5 on 2023-01-24 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SneakerModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('colorway', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=20)),
                ('release_year', models.CharField(max_length=20)),
                ('retail_price', models.CharField(max_length=20)),
                ('cover_image', models.CharField(max_length=300)),
                ('brand', models.ManyToManyField(blank=True, related_name='models', to='brands.brand')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
