# Generated by Django 4.1.5 on 2023-01-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakerModels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sneakermodels',
            old_name='sneaker_model',
            new_name='brand',
        ),
    ]
